spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/authenticationdb
    username: root
    password: amb123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 7070

app:
  jwt:
    secret: Hs9f!8Qw#2kLmPz7@vR3tXy1bNc5uJg4Dz6WpErQ
    expiration-ms: 3600000   # 1 hour
  otp:
    length: 6
    expiry-ms: 300000        # 5 minutes
