spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: root
      password: amb123
      host: localhost
      port: 27017
      database: customerdb
      authentication-database: admin

server:
  port: 8092
